package gvars

import "Nux-xader/kaiweb/models"

var (
	TeleID         *string
	DeviceID       *string
	LicenseExpTime int64
)
var STATIONS = []models.Station{
	{Name: "TANJUNG KARANG", Code: "TNK"},
	{Name: "LABUAN RATU", Code: "LAR"},
	{Name: "REJOSARI", Code: "RJS"},
	{Name: "TEGINENENG", Code: "TGI"},
	{Name: "BEKRI", Code: "BKI"},
	{Name: "HAJI PEMANGGILAN", Code: "HJP"},
	{Name: "SULUSUBAN", Code: "SLS"},
	{Name: "KOTABUMI", Code: "KB"},
	{Name: "CEMPAKA", Code: "CEP"},
	{Name: "KETAPANG", Code: "KTP"},
	{Name: "NEGARA RATU", Code: "NRR"},
	{Name: "TULUNG BUYUT", Code: "TLY"},
	{Name: "NEGERIAGUNG", Code: "NGN"},
	{Name: "BLAMBANGAN UMPU", Code: "BBU"},
	{Name: "GIHAM", Code: "GHM"},
	{Name: "WAYTUBA", Code: "WAY"},
	{Name: "MARTAPURA", Code: "MP"},
	{Name: "GILAS", Code: "GLS"},
	{Name: "SEPANCAR", Code: "SPC"},
	{Name: "LUBUKRUKRAM", Code: "LRM"},
	{Name: "PENINJAWAN", Code: "PNW"},
	{Name: "METUR", Code: "MET"},
	{Name: "PENIMUR", Code: "PNM"},
	{Name: "NIRU", Code: "NRU"},
	{Name: "BELIMBING PENDOPO", Code: "BIB"},
	{Name: "GUNUNG MEGANG", Code: "GNM"},
	{Name: "UJAN MAS", Code: "UJM"},
	{Name: "MUARAGULA", Code: "MRL"},
	{Name: "KOTA PADANG", Code: "KOP"},
	{Name: "MUARASALING", Code: "MSL"},
	{Name: "TEBING TINGGI", Code: "TI"},
	{Name: "SAUNG NAGA", Code: "SNA"},
	{Name: "SUKARAJA", Code: "SUA"},
	{Name: "BUNGAMAS", Code: "BGM"},
	{Name: "LAHAT", Code: "LT"},
	{Name: "SUKACINTA", Code: "SCT"},
	{Name: "BAJARSARI", Code: "BJI"},
	{Name: "MUARA ENIM", Code: "ME"},
	{Name: "PRABUMULIH", Code: "PBM"},
	{Name: "LEMBAK", Code: "LEB"},
	{Name: "KARANG ENDA", Code: "KED"},
	{Name: "GOMBONG", Code: "GB"},
	{Name: "SERDANG", Code: "SDN"},
	{Name: "PAYAKABUNG", Code: "PYK"},
	{Name: "KERTAPATI", Code: "KPT"},
	{Name: "TARAHAN", Code: "THN"},
	{Name: "LUBUK LINGGAU", Code: "LLG"},
	{Name: "TANJUNGENIM BARU", Code: "TMB"},
	{Name: "BATURAJA", Code: "BTA"},
	{Name: "MANGGARAI", Code: "MRI"},
	{Name: "TANAHABANG", Code: "THB"},
	{Name: "GAMBIR", Code: "GMR"},
	{Name: "JUANDA", Code: "JUA"},
	{Name: "ANCOL", Code: "AC"},
	{Name: "JAKARTA KOTA", Code: "JAKK"},
	{Name: "KAMPUNG BANDAN", Code: "KPB"},
	{Name: "ANGKE", Code: "AK"},
	{Name: "DURI", Code: "DU"},
	{Name: "PALMERAH", Code: "PLM"},
	{Name: "KEBAYORAN", Code: "KBY"},
	{Name: "PONDOKRANJI", Code: "PDJ"},
	{Name: "SUDIMARA", Code: "SDM"},
	{Name: "SERPONG", Code: "SRP"},
	{Name: "PARUNGPANJANG", Code: "PRP"},
	{Name: "CILEJIT", Code: "CJT"},
	{Name: "TENJO", Code: "TEJ"},
	{Name: "TIGARAKSA", Code: "TGS"},
	{Name: "MAJA", Code: "MJ"},
	{Name: "CILEGON", Code: "CLG"},
	{Name: "MERAK", Code: "MER"},
	{Name: "KRADENAN", Code: "KNN"},
	{Name: "JAMBON", Code: "JBN"},
	{Name: "LAWANG", Code: "LW"},
	{Name: "MALANG", Code: "ML"},
	{Name: "MALANG KOTA LAMA", Code: "MLK"},
	{Name: "KEPANJEN", Code: "KPN"},
	{Name: "SUMBERPUCUNG", Code: "SBP"},
	{Name: "KESAMBEN", Code: "KSB"},
	{Name: "WLINGI", Code: "WG"},
	{Name: "BLITAR", Code: "BL"},
	{Name: "NGUNUT", Code: "NT"},
	{Name: "TULUNGAGUNG", Code: "TA"},
	{Name: "NGUJANG", Code: "NJG"},
	{Name: "KEDIRI", Code: "KD"},
	{Name: "PAPAR", Code: "PPR"},
	{Name: "SUKABUMI", Code: "SI"},
	{Name: "PASARSENEN", Code: "PSE"},
	{Name: "JATINEGARA", Code: "JNG"},
	{Name: "GUMILIR", Code: "GM"},
	{Name: "CILACAP", Code: "CP"},
	{Name: "WONOGIRI", Code: "WNG"},
	{Name: "JAKARTA GUDANG", Code: "JAKG"},
	{Name: "NAMBO", Code: "NMO"},
	{Name: "CIBINONG", Code: "CBN"},
	{Name: "DOLOKMERANGIR", Code: "DMR"},
	{Name: "BAJALINGGEI", Code: "BJL"},
	{Name: "LAUT TADOR", Code: "LTD"},
	{Name: "BANDARTINGGI", Code: "BDT"},
	{Name: "BAHLIAS", Code: "BLI"},
	{Name: "PERLANAAN", Code: "PRA"},
	{Name: "LIMAPULUH", Code: "LMP"},
	{Name: "SEI BEJANGKAR", Code: "SBJ"},
	{Name: "KISARAN", Code: "KIS"},
	{Name: "TELUKDALAM", Code: "TUK"},
	{Name: "PULURAJA", Code: "PUR"},
	{Name: "AEKLOBA", Code: "AKB"},
	{Name: "MAMBANGMUDA", Code: "MBM"},
	{Name: "SITUNGIR", Code: "SIU"},
	{Name: "PAMINGKE", Code: "PME"},
	{Name: "PADANGHALABAN", Code: "PHA"},
	{Name: "MARBAU", Code: "MBU"},
	{Name: "TANJUNGBALAI", Code: "TNB"},
	{Name: "TEBING TINGGI", Code: "TBI"},
	{Name: "BAMBAN", Code: "BMB"},
	{Name: "RAMPAH", Code: "RPH"},
	{Name: "TELUK MENGKUDU", Code: "TKE"},
	{Name: "LIDAHTANAH", Code: "LDT"},
	{Name: "PERBAUNGAN", Code: "PBA"},
	{Name: "LUBUKPAKAM", Code: "LBP"},
	{Name: "ARASKABU", Code: "ARB"},
	{Name: "BATANGKUIS", Code: "BTK"},
	{Name: "BANDARHALIPAH", Code: "BAP"},
	{Name: "MEDAN", Code: "MDN"},
	{Name: "PULUBRAYAN", Code: "PUB"},
	{Name: "RANTAUPRAPAT", Code: "RAP"},
	{Name: "SIANTAR", Code: "SIR"},
	{Name: "RANCAEKEK", Code: "RCK"},
	{Name: "GEDEBAGE", Code: "GDB"},
	{Name: "KIARACONDONG", Code: "KAC"},
	{Name: "BANDUNG", Code: "BD"},
	{Name: "CIMAHI", Code: "CMI"},
	{Name: "PADALARANG", Code: "PDL"},
	{Name: "PLERED", Code: "PLD"},
	{Name: "PURWAKARTA", Code: "PWK"},
	{Name: "CIKAMPEK", Code: "CKP"},
	{Name: "KARAWANG", Code: "KW"},
	{Name: "CIKARANG", Code: "CKR"},
	{Name: "BEKASI", Code: "BKS"},
	{Name: "CAKUNG", Code: "CUK"},
	{Name: "KLENDER BARU", Code: "KLDB"},
	{Name: "BUARAN", Code: "BUA"},
	{Name: "KLENDER", Code: "KLD"},
	{Name: "CIPINANG", Code: "CPN"},
	{Name: "PONDOKJATI", Code: "POK"},
	{Name: "RAJAWALI", Code: "RJW"},
	{Name: "BANJAR", Code: "BJR"},
	{Name: "CIAMIS", Code: "CI"},
	{Name: "TASIKMALAYA", Code: "TSM"},
	{Name: "CIPEUNDEUY", Code: "CPD"},
	{Name: "CIBATU", Code: "CB"},
	{Name: "LELES", Code: "LL"},
	{Name: "CICALENGKA", Code: "CCL"},
	{Name: "KUTOARJO", Code: "KTA"},
	{Name: "JENAR", Code: "JN"},
	{Name: "WOJO", Code: "WJ"},
	{Name: "KEDUNDANG", Code: "KDG"},
	{Name: "WATES", Code: "WT"},
	{Name: "YOGYAKARTA", Code: "YK"},
	{Name: "LEMPUYANGAN", Code: "LPN"},
	{Name: "KLATEN", Code: "KT"},
	{Name: "PURWOSARI", Code: "PWS"},
	{Name: "SOLO BALAPAN", Code: "SLO"},
	{Name: "SALEM", Code: "SLM"},
	{Name: "GUNDIH", Code: "GD"},
	{Name: "KARANGSONO", Code: "KSO"},
	{Name: "TELAWA", Code: "TW"},
	{Name: "KEDUNGJATI", Code: "KEJ"},
	{Name: "BRUMBUNG", Code: "BBG"},
	{Name: "ALASTUA", Code: "ATA"},
	{Name: "SEMARANG TAWANG", Code: "SMT"},
	{Name: "SEMARANG PONCOL", Code: "SMC"},
	{Name: "KALIWUNGU", Code: "KLN"},
	{Name: "WELERI", Code: "WLR"},
	{Name: "BATANG", Code: "BTG"},
	{Name: "PEKALONGAN", Code: "PK"},
	{Name: "PEMALANG", Code: "PML"},
	{Name: "PEMALANG", Code: "PML"},
	{Name: "SLAWI", Code: "SLW"},
	{Name: "TEGAL", Code: "TG"},
	{Name: "BREBES", Code: "BB"},
	{Name: "TANJUNG", Code: "TGN"},
	{Name: "LOSARI", Code: "LOS"},
	{Name: "BABAKAN", Code: "BBK"},
	{Name: "CILEDUG", Code: "CLD"},
	{Name: "PEGADENBARU", Code: "PGB"},
	{Name: "HAURGEULIS", Code: "HGL"},
	{Name: "TERISI", Code: "TIS"},
	{Name: "JATIBARANG", Code: "JTB"},
	{Name: "ARJAWINANGUN", Code: "AWN"},
	{Name: "CIREBON", Code: "CN"},
	{Name: "CIREBON PRUJAKAN", Code: "CNP"},
	{Name: "KETANGGUNGAN", Code: "KGG"},
	{Name: "PRUPUK", Code: "PPK"},
	{Name: "BUMIAYU", Code: "BMA"},
	{Name: "PURWOKERTO", Code: "PWT"},
	{Name: "KEBASEN", Code: "KBS"},
	{Name: "MAOS", Code: "MA"},
	{Name: "JERUKLEGI", Code: "JRL"},
	{Name: "SIDAREJA", Code: "SDR"},
	{Name: "GANDRUNGMANGUN", Code: "GDM"},
	{Name: "GUBUG", Code: "GUB"},
	{Name: "CISAAT", Code: "CSA"},
	{Name: "KARANGTENGAH", Code: "KE"},
	{Name: "CIBADAK", Code: "CBD"},
	{Name: "PARUNG KUDA", Code: "PRK"},
	{Name: "CICURUG", Code: "CCR"},
	{Name: "CIGOMBONG", Code: "CGB"},
	{Name: "MASENG", Code: "MSG"},
	{Name: "BATUTULIS", Code: "BTT"},
	{Name: "BOGOR", Code: "BOO"},
	{Name: "CIGADING", Code: "CGD"},
	{Name: "KROYA", Code: "KYA"},
	{Name: "SUMPIUH", Code: "SPH"},
	{Name: "GOMBONG", Code: "GB"},
	{Name: "KARANGANYAR", Code: "KA"},
	{Name: "KEBUMEN", Code: "KM"},
	{Name: "KUTOWINANGUN", Code: "KWN"},
	{Name: "GAMBRINGAN", Code: "GBN"},
	{Name: "NGROMBO", Code: "NBO"},
	{Name: "WARU", Code: "WR"},
	{Name: "SEPANJANG", Code: "SPJ"},
	{Name: "KRIAN", Code: "KRN"},
	{Name: "MOJOKERTO", Code: "MR"},
	{Name: "CURAHMALANG", Code: "CRM"},
	{Name: "JOMBANG", Code: "JG"},
	{Name: "SEMBUNG", Code: "SMB"},
	{Name: "KERTOSONO", Code: "KTS"},
	{Name: "NGANJUK", Code: "NJ"},
	{Name: "CARUBAN", Code: "CRB"},
	{Name: "MADIUN", Code: "MN"},
	{Name: "GENENG", Code: "GG"},
	{Name: "PARON", Code: "PA"},
	{Name: "KEDUNGGALAR", Code: "KG"},
	{Name: "WALIKUKUN", Code: "WK"},
	{Name: "SRAGEN", Code: "SR"},
	{Name: "PALUR", Code: "PL"},
	{Name: "SOLOJEBRES", Code: "SK"},
	{Name: "ROGOJAMPI", Code: "RGP"},
	{Name: "TEMUGURUH", Code: "TGR"},
	{Name: "KALISETAIL", Code: "KSL"},
	{Name: "SUMBER WADUNG", Code: "SWD"},
	{Name: "GLENMORE", Code: "GLM"},
	{Name: "KALIBARU", Code: "KBR"},
	{Name: "GARAHAN", Code: "GRN"},
	{Name: "KALISAT", Code: "KLT"},
	{Name: "ARJASA", Code: "AJ"},
	{Name: "JEMBER", Code: "JR"},
	{Name: "RAMBIPUJI", Code: "RBP"},
	{Name: "BANGSALSARI", Code: "BSS"},
	{Name: "TANGGUL", Code: "TGL"},
	{Name: "KLAKAH", Code: "KK"},
	{Name: "PROBOLINGGO", Code: "PB"},
	{Name: "BAYEMAN", Code: "BYM"},
	{Name: "PASURUAN", Code: "PS"},
	{Name: "BANGIL", Code: "BG"},
	{Name: "SIDOARJO", Code: "SDA"},
	{Name: "WONOKROMO", Code: "WO"},
	{Name: "SURABAYA GUBENG", Code: "SGU"},
	{Name: "SURABAYA KOTA", Code: "SB"},
	{Name: "SURABAYA PASAR TURI", Code: "SBI"},
	{Name: "LAMONGAN", Code: "LMG"},
	{Name: "BOJONEGORO", Code: "BJ"},
	{Name: "CEPU", Code: "CU"},
	{Name: "WADU", Code: "WDU"},
	{Name: "RANDUBLATUNG", Code: "RBG"},
	{Name: "DOPLANG", Code: "DPL"},
	{Name: "CIMPARUH", Code: "CPH"},
	{Name: "PASOSO", Code: "POO"},
	{Name: "MAGETAN", Code: "MAG"},
	{Name: "KETAPANG", Code: "KTG"},
	{Name: "BABAT", Code: "BBT"},
	{Name: "LECES", Code: "LEC"},
	{Name: "WANARAJA", Code: "WNR"},
	{Name: "GLUMBANG", Code: "GLB"},
	{Name: "TUNTANG", Code: "TTG"},
	{Name: "NGUJANG", Code: "NJG"},
	{Name: "BOGOR PALEDANG", Code: "BOP"},
	{Name: "SUNGAI TUHA", Code: "SGT"},
	{Name: "WAY PISANG", Code: "WAP"},
	{Name: "SAWAH LUNTO", Code: "SWL"},
	{Name: "SINGKARAK", Code: "SKA"},
	{Name: "BATU TEBAL", Code: "BTL"},
	{Name: "PASAR USANG", Code: "PRU"},
	{Name: "BUKITPUTUS", Code: "BKP"},
	{Name: "MUARA KALABAN", Code: "MKL"},
	{Name: "PIDADA", Code: "PID"},
	{Name: "PASIRJENGKOL", Code: "PSJ"},
	{Name: "NGAWI", Code: "NGW"},
	{Name: "BANYUWANGI KOTA", Code: "BWI"},
	{Name: "GARUT", Code: "GRT"},
	{Name: "KANTOR PUSAT", Code: "KP"},
}
